# Numpy

1.Shape of array

2.Dimension of array

3.Reshape of array

4.arange function of array

5.Ones

6.Zeros

7.linspace

8.logspace

9.random.rand function

10.random.randn function

11.random.randint function

12.random.rand_sample function


In [2]:
#lets understand how to create Numpy array
import numpy as np

In [4]:
arr=np.array([1,2,3,4,5])

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

# 1.Shape

Shape is inbuilt funtion to check shape of array i.e How many row and column exist in array .
For 1 D array 1 row exist and for 2D array atleast on row and one column exist


In [63]:
arr.shape

(5,)

# 2. Dimension Checking

 .ndim is inbuilt function to check array dimenstion

In [13]:
arr.ndim

1

In [15]:
arr1=np.array([[1,2,3,4,5,6]])

In [16]:
arr1

array([[1, 2, 3, 4, 5, 6]])

In [17]:
type(arr1)


numpy.ndarray

In [18]:
arr1.shape

(1, 6)

In [19]:
arr1.ndim

2

#  3.Reshape

reshape is inbuilt function to convert array into user desire row and column .important point is to take care number of row and 
column not exeeds out of range from existing array element

In [20]:
#reshape

arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

#  4.arange 

used to generate array in sequence of desire with required step size 

In [40]:
##arange function

arr2=np.arange(0,10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr3=np.arange(0,20,2)
arr3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
#reshape

a=arr3.reshape(2,5)

In [46]:
a[0:1,1:2]


array([[2]])

#  5.ones

Used to generate number of 1 as per requirement 

In [54]:
arr4=np.ones(3)
arr5=np.ones(10)

In [56]:
arr5
arr4

array([1., 1., 1.])

#  6.Zeros

Used to generate number of 0 as per requirement 

In [58]:
arr6=np.zeros(5)

In [59]:
arr6

array([0., 0., 0., 0., 0.])

# 7. Linspace


Used to generate array in equal space distribution in float. each consequtive number difference is equal

In [62]:
arr7=np.linspace(0,10,8)
arr7

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

# 8.logspace

Used to generate array in equal space distribution in log form. each consequtive number difference is equal in log value form

In [64]:
arr8=np.logspace(0,10,8)
arr8

array([1.00000000e+00, 2.68269580e+01, 7.19685673e+02, 1.93069773e+04,
       5.17947468e+05, 1.38949549e+07, 3.72759372e+08, 1.00000000e+10])

# 9. Random.rand

In [65]:
a=np.random.rand(10)

In [67]:
a

array([0.95183592, 0.70504822, 0.27050001, 0.20524758, 0.62445993,
       0.59918943, 0.32963793, 0.39191094, 0.20476468, 0.88674686])

# 10.Random.randn

In [71]:
b=np.random.randn(20)

In [72]:
b

array([ 2.52429543,  0.1882509 , -2.34223338, -0.14093082,  1.42780582,
       -0.42194124, -1.09614584, -0.06760819, -0.3276524 , -1.6797925 ,
       -0.98618191,  0.58773944, -1.55378278,  0.72706058,  0.68062638,
        0.26216245,  1.62256272,  1.29930212,  0.24269412, -0.68638495])

# 11.Random.randint

In [78]:
c=np.random.randint(10)

In [77]:
c

4

# 12.Random.sample

In [81]:
d=np.random.sample(10)

In [82]:
d

array([0.2514192 , 0.15200338, 0.12587385, 0.51360204, 0.28275845,
       0.99392791, 0.53817836, 0.96897995, 0.26734259, 0.89360769])